---
- name: install tomcat server
  hosts: all
  become: true
  vars:
    - tomcat_url: https://mirrors.estointernet.in/apache/tomcat/tomcat-10/v10.0.18/bin/apache-tomcat-10.0.18.tar.gz
	- tomcat_package: apache-tomcat-10.0.18
  tasks:
  - name: install java
    yum: 
	  name: java
	  state: latest
  - name: download tomcat server package
    get_url: 
	  url: "{{ tomcat_url }}"
      dest: /usr/local
  - name: extarct tomcat package
    unarchieve:
      src: /usr/local/{{tomcat_package}}.tar.gz
	  dest: /usr/local
	  remote_src: yes
	   
  - name: start tomcat process
    shell: nohup /usr/local/{{ tomcat_package }}/bin/startup.sh
